### PR TITLE
Big (important) fix xD

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by stephan-gh** [comment]
:-1:

**Comment by jamierocks** [comment]
<3

**Comment by caseif** [comment]
Fixed via [73b0b82](https://github.com/caseif/Flint/commit/73b0b8281fb2acb9e06de260cbcec5169ba3e709), ya dingus.

**Comment by jamierocks** [comment]
22:45 jamierocks:
NOOOOOOOOOO
22:45 jamierocks:
why you do 'dis

**Pull request closed without merging**
